import { all } from "axios";
import { createContext, useState, useContext, useEffect, act } from "react";

const LanguageContext = createContext();

export const translations = {
  en: {
    // ==================== NAVIGATION ====================
    dashboard: "Dashboard",
    myTickets: "My Tickets",
    allTickets: "All Tickets",
    services: "Services",
    users: "Users",
    departments: "Departments",
    roles: "Roles",
    logout: "Logout",
    profile: "Profile",
    settings: "Settings",  
    // ==================== COMMON ACTIONS ====================
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    create: "Create",
    update: "Update",
    submit: "Submit",
    close: "Close",
    back: "Back",
    next: "Next",
    previous: "Previous",
    confirm: "Confirm",
    search: "Search",
    filter: "Filter",
    reset: "Reset",
    clear: "Clear",
    apply: "Apply",
    download: "Download",
    upload: "Upload",
    export: "Export",
    import: "Import",
    print: "Print",
    refresh: "Refresh",   
    // ==================== COMMON PHRASES ====================
    welcome: "Welcome",
    welcomeBack: "Welcome back",
    loading: "Loading...",
    noData: "No data available",
    noResults: "No results found",
    searchResults: "Search results",
    showing: "Showing",
    of: "of",
    results: "results",
    page: "Page",
    rowsPerPage: "Rows per page",
    selectAll: "Select all",
    selected: "selected", 
    submittedBy: "Submitted by",
    // ==================== FORM FIELDS ====================
    yourName: "Your Name",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    phone: "Phone",
    address: "Address",
    city: "City",
    country: "Country",
    postalCode: "Postal Code",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    male: "Male",
    female: "Female", 
    describeInDetail: "Describe your request in detail...",
    // ==================== VALIDATION MESSAGES ====================
    required: "This field is required",
    invalidEmail: "Invalid email format",
    invalidPhone: "Invalid phone number",
    passwordMismatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 8 characters",
    fieldRequired: "All fields are required",
    pleaseSelect: "Please select",
    selectOption: "Select an option",  
    // ==================== AUTH & LOGIN ====================
    login: "Login",
    loginTitle: "Login to your account",
    register: "Register",
    registerTitle: "Create new account",
    forgotPassword: "Forgot password?",
    rememberMe: "Remember me",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out", 
    // ==================== TICKETS ====================
    ticket: "Ticket",
    tickets: "Tickets",
    newTicket: "New Request",
    createTicket: "Create Ticket",
    submitRequest: "Submit Request",
    ticketDetails: "Ticket Details",
    ticketNumber: "Ticket Number",
    ticketTitle: "Request Title",
    ticketDescription: "Description",
    ticketCreated: "Ticket Created",
    ticketUpdated: "Ticket Updated",
    ticketClosed: "Ticket Closed",
    noTickets: "No tickets yet. Submit your first request!",
    noTicketsFound: "No tickets found",
    trackYourRequests: "Track all your submitted requests",
    fillDetailsBelow: "Fill in the details below to submit your IT request",
    describeInDetail: "Describe your request in detail...",
    ticketSubmittedSuccess: "Ticket submitted successfully! Redirecting...",
    assignToMe: "Assign to Me",
    assignedToYou: "Assigned to You",
    unassigned: "Unassigned",
    manageResolveTickets: "Manage and resolve tickets assigned to you",
      // ==================== PRIORITY ====================
    priority: "Priority",
    low: "Low",
    medium: "Medium",
    high: "High",
    critical: "Critical",
    urgent: "Urgent",  
    // ==================== STATUS ====================
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    new: "New",
    assigned: "Assigned",
    in_progress: "In Progress",
    resolved: "Resolved",
    closed: "Closed",
    open: "Open",
    completed: "Completed",   
    // ==================== USERS ====================
    user: "User",
    userName: "User Name",
    fullName: "Full Name",
    role: "Role",
    department: "Department",
    agentDashboard: "Agent Dashboard",
    totalUsers: "Total Users",
    activeUsers: "Active Users",
    pendingUsers: "Pending Activation",
    userManagement: "User Management",
    addUser: "Add User",
    addNewUser: "Add New User",
    editUser: "Edit User",
    deleteUser: "Delete User",
    activateUser: "Activate User",
    deactivateUser: "Deactivate User",
    userCreated: "User created successfully",
    userUpdated: "User updated successfully",
    userDeleted: "User deleted successfully",
    searchUsers: "Search users...",
    noUsersFound: "No users found",
    allUsers: "All Users", 
      pendingActivation: "Pending Activation",  
    // ==================== DEPARTMENTS ====================
    departmentManagement: "Department Management",
    departmentName: "Department Name",
    departmentHead: "Department Head",
    addDepartment: "Add Department",
    editDepartment: "Edit Department",
    deleteDepartment: "Delete Department",
    noDepartments: "No departments found",   
    saveChanges: "Save Changes",
    selectDepartment: "Select Department",
    // ==================== ROLES ====================
    roleName: "Role Name",
    roleDescription: "Role Description",
    permissions: "Permissions",
    addRole: "Add Role",
    editRole: "Edit Role",
    deleteRole: "Delete Role",
    noRoles: "No roles found",
    roleManagement: "Role Management", 
    selectRole: "Select Role",   
    // ==================== SERVICES ====================
    service: "Service",
    serviceName: "Service Name",
    serviceDescription: "Service Description",
    serviceCategory: "Service Category",
    serviceCatalog: "Service Catalog",
    browseServices: "Browse Services",
    requestService: "Request Service",
    addService: "Add Service",
    editService: "Edit Service",
    deleteService: "Delete Service",
    noServices: "No services available",
    selectService: "Select Service",
    slaHours: "h SLA",
    expectedResolution: "Expected Resolution",
    hours: "hours",    
    // ==================== CATEGORIES ====================
    category: "Category",
    hardware: "Hardware",
    software: "Software",
    network: "Network",
    account: "Account",
    access: "Access",
    security: "Security",
    support: "Support",
    maintenance: "Maintenance",
    // ==================== DASHBOARD ====================
    manageOrganization: "Manage your organization from this dashboard",
    quickOverview: "Quick Overview",
    recentActivity: "Recent Activity",
    statistics: "Statistics",
    analytics: "Analytics",
    reports: "Reports",
    // ==================== STATS CARDS ====================
    total: "Total",
    today: "Today",
    thisWeek: "This Week",
    thisMonth: "This Month",
    newRequests: "New Requests",
    pendingApproval: "Pending Approval",
    resolvedToday: "Resolved Today",
    averageResponseTime: "Average Response Time",    
    // ==================== ACTIONS ====================
    viewDetails: "View Details",
    moreInfo: "More Info",
    actions: "Actions",
    options: "Options",
    manage: "Manage",
    configure: "Configure",   
    // ==================== TIME & DATE ====================
    createdAt: "Created At",
    updatedAt: "Updated At",
    createdBy: "Created By",
    assignedTo: "Assigned To",
    resolvedAt: "Resolved At",
    closedAt: "Closed At",
    date: "Date",
    time: "Time",
    dateTime: "Date & Time",   
    // ==================== CONFIRMATIONS ====================
    areYouSure: "Are you sure?",
    confirmDelete: "Are you sure you want to delete this?",
    confirmAction: "Are you sure you want to proceed?",
    cannotBeUndone: "This action cannot be undone",
    yes: "Yes",
    no: "No",    
    // ==================== SUCCESS MESSAGES ====================
    success: "Success",
    operationSuccessful: "Operation completed successfully",
    savedSuccessfully: "Saved successfully",
    deletedSuccessfully: "Deleted successfully",
    updatedSuccessfully: "Updated successfully",
    createdSuccessfully: "Created successfully",    
    // ==================== ERROR MESSAGES ====================
    error: "Error",
    somethingWentWrong: "Something went wrong",
    errorOccurred: "An error occurred",
    tryAgain: "Please try again",
    contactSupport: "Contact support if the problem persists",
    networkError: "Network error. Please check your connection",
    unauthorized: "Unauthorized access",
    accessDenied: "Access denied",
    notFound: "Not found", 
    // ==================== NOTIFICATIONS ====================
    notifications: "Notifications",
    noNotifications: "No notifications",
    markAsRead: "Mark as read",
    markAllAsRead: "Mark all as read",
    clearAll: "Clear all",
    // ==================== HELP & INFO ====================
    help: "Help",
    documentation: "Documentation",
    support: "Support",
    contactUs: "Contact Us",
    faq: "FAQ",
    // ==================== FOOTER ====================
    allRightsReserved: "All rights reserved",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    version: "Version",
  },
  
  fr: {
      // ==================== NAVIGATION ==================== 
    dashboard: "Tableau de bord",
    myTickets: "Mes Tickets",
    allTickets: "Tous les Tickets",
    services: "Services",
    users: "Utilisateurs",
    departments: "Départements",
    roles: "Rôles",
    logout: "Déconnexion",
    profile: "Profil",
    settings: "Paramètres",
    // ==================== COMMON ACTIONS ====================
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    add: "Ajouter",
    activate: "Activer",
    deactivate: "Désactiver",
    create: "Créer",
    update: "Mettre à jour",
    submit: "Soumettre",
    close: "Fermer",
    back: "Retour",
    next: "Suivant",
    previous: "Précédent",
    confirm: "Confirmer",
    search: "Rechercher",
    filter: "Filtrer",
    reset: "Réinitialiser",
    clear: "Effacer",
    apply: "Appliquer",
    download: "Télécharger",
    upload: "Téléverser",
    export: "Exporter",
    import: "Importer",
    print: "Imprimer",
    refresh: "Actualiser",
    // ==================== COMMON PHRASES ====================
    welcome: "Bienvenue",
    welcomeBack: "Bon retour",
    loading: "Chargement...",
    noData: "Aucune donnée disponible",
    noResults: "Aucun résultat trouvé",
    searchResults: "Résultats de recherche",
    showing: "Affichage",
    of: "de",
    results: "résultats",
    page: "Page",
    rowsPerPage: "Lignes par page",
    selectAll: "Tout sélectionner",
    selected: "sélectionné(s)",
    submittedBy: "Soumis par",
    title: "Titre",
    // ==================== FORM FIELDS ====================
    yourName: "Votre nom",
    firstName: "Prénom",
    lastName: "Nom",
    email: "Email",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    phone: "Téléphone",
    address: "Adresse",
    city: "Ville",
    country: "Pays",
    postalCode: "Code postal",
    dateOfBirth: "Date de naissance",
    gender: "Genre",
    male: "Homme",
    female: "Femme",
    describeInDetail: "Décrivez votre demande en détail...",
     // ==================== VALIDATION MESSAGES ====================
    required: "Ce champ est requis",
    invalidEmail: "Format d'email invalide",
    invalidPhone: "Numéro de téléphone invalide",
    passwordMismatch: "Les mots de passe ne correspondent pas",
    passwordTooShort: "Le mot de passe doit comporter au moins 8 caractères",
    fieldRequired: "Tous les champs sont requis",
    pleaseSelect: "Veuillez sélectionner",
    selectOption: "Sélectionnez une option",
     // ==================== AUTH & LOGIN ====================
    login: "Connexion",
    loginTitle: "Connectez-vous à votre compte",
    register: "S'inscrire",
    registerTitle: "Créer un nouveau compte",
    forgotPassword: "Mot de passe oublié ?",
    rememberMe: "Se souvenir de moi",
    dontHaveAccount: "Vous n'avez pas de compte ?",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    signIn: "Se connecter",
    signUp: "S'inscrire",
    signOut: "Se déconnecter",
    // ==================== TICKETS ====================  
    ticket: "Ticket",
    tickets: "Tickets",
    newTicket: "Nouvelle demande",
    createTicket: "Créer un ticket",
    submitRequest: "Soumettre la demande",
    ticketDetails: "Détails du ticket",
    ticketNumber: "Numéro du ticket",
    ticketTitle: "Titre de la demande",
    ticketDescription: "Description",
    ticketCreated: "Ticket créé",
    ticketUpdated: "Ticket mis à jour",
    ticketClosed: "Ticket fermé",
    noTickets: "Aucun ticket pour le moment. Soumettez votre première demande !",
    noTicketsFound: "Aucun ticket trouvé",
    trackYourRequests: "Suivez toutes vos demandes soumises",
    fillDetailsBelow: "Remplissez les détails ci-dessous pour soumettre votre demande informatique",
    describeInDetail: "Décrivez votre demande en détail...",
    ticketSubmittedSuccess: "Ticket soumis avec succès ! Redirection...",
    assignToMe: "M'assigner",
    assignedToYou: "Assigné à vous",
    unassigned: "Non assigné",
    manageResolveTickets: "Gérez et résolvez les tickets qui vous sont assignés",
      // ==================== PRIORITY ====================
    priority: "Priorité",
    low: "Basse",
    medium: "Moyenne",
    high: "Haute",
    critical: "Critique",
    urgent: "Urgent",
      // ==================== STATUS ====================
    status: "Statut",
    active: "Actif",
    inactive: "Inactif",
    pending: "En attente",
    approved: "Approuvé",
    rejected: "Rejeté",
    all: "Tous",
    new: "Nouveau",
    assigned: "Assigné",
    in_progress: "En cours",
    resolved: "Résolu",
    closed: "Fermé",
    open: "Ouvert",
    completed: "Terminé",
    // ==================== USERS ====================
    user: "Utilisateur",
    userName: "Nom d'utilisateur",
    fullName: "Nom complet",
    role: "Rôle",
    department: "Département",
    agentDashboard: "Tableau de bord de l'agent",
    totalUsers: "Total des utilisateurs",
    activeUsers: "Utilisateurs actifs",
    pendingUsers: "En attente d'activation",
    userManagement: "Gestion des utilisateurs",
    addUser: "Ajouter un utilisateur",
    addNewUser: "Ajouter un nouvel utilisateur",
    editUser: "Modifier l'utilisateur",
    deleteUser: "Supprimer l'utilisateur",
    activateUser: "Activer l'utilisateur",
    deactivateUser: "Désactiver l'utilisateur",
    userCreated: "Utilisateur créé avec succès",
    userUpdated: "Utilisateur mis à jour avec succès",
    userDeleted: "Utilisateur supprimé avec succès",
    searchUsers: "Rechercher des utilisateurs...",
    noUsersFound: "Aucun utilisateur trouvé",
    allUsers: "Tous les utilisateurs",
    pendingActivation: "En attente d'activation",
    // ==================== DEPARTMENTS ==================== 
    departmentManagement: "Gestion des départements",
    departmentName: "Nom du département",
    departmentHead: "Chef de département",
    addDepartment: "Ajouter un département",
    editDepartment: "Modifier le département",
    deleteDepartment: "Supprimer le département",
    noDepartments: "Aucun département trouvé",
    saveChanges: "Enregistrer les modifications",
    selectDepartment: "Sélectionnez un département",
    // ==================== ROLES ====================
    roleName: "Nom du rôle",
    roleDescription: "Description du rôle",
    permissions: "Permissions",
    addRole: "Ajouter un rôle",
    editRole: "Modifier le rôle",
    deleteRole: "Supprimer le rôle",
    noRoles: "Aucun rôle trouvé",
    roleManagement: "Gestion des rôles",
    selectRole: "Sélectionnez un rôle",
    // ==================== SERVICES ====================
    service: "Service",
    serviceName: "Nom du service",
    serviceDescription: "Description du service",
    serviceCategory: "Catégorie du service",
    serviceCatalog: "Catalogue de services",
    browseServices: "Parcourir les services",
    requestService: "Demander un service",
    addService: "Ajouter un service",
    editService: "Modifier le service",
    deleteService: "Supprimer le service",
    noServices: "Aucun service disponible",
    selectService: "Sélectionnez un service",
    slaHours: "h SLA",
    expectedResolution: "Résolution attendue",
    hours: "heures",
    // ==================== CATEGORIES ====================
    category: "Catégorie",
    hardware: "Matériel",
    software: "Logiciel",
    network: "Réseau",
    account: "Compte",
    access: "Accès",
    security: "Sécurité",
    support: "Support",
    maintenance: "Maintenance",
    other: "Autre",
      // ==================== DASHBOARD ====================
    manageOrganization: "Gérez votre organisation depuis ce tableau de bord",
    quickOverview: "Aperçu rapide",
    recentActivity: "Activité récente",
    statistics: "Statistiques",
    analytics: "Analyses",
    reports: "Rapports",
    // ==================== STATS CARDS ====================
    total: "Total",
    today: "Aujourd'hui",
    thisWeek: "Cette semaine",
    thisMonth: "Ce mois-ci",
    newRequests: "Nouvelles demandes",
    pendingApproval: "En attente d'approbation",
    resolvedToday: "Résolus aujourd'hui",
    averageResponseTime: "Temps de réponse moyen",
    // ==================== ACTIONS ====================
    viewDetails: "Voir les détails",
    moreInfo: "Plus d'infos",
    actions: "Actions",
    options: "Options",
    manage: "Gérer",
    configure: "Configurer",
    // ==================== TIME & DATE ====================
    createdAt: "Créé le",
    updatedAt: "Mis à jour le",
    createdBy: "Créé par",
    assignedTo: "Assigné à",
    resolvedAt: "Résolu le",
    closedAt: "Fermé le",
    date: "Date",
    time: "Heure",
    dateTime: "Date & Heure",
    // ==================== CONFIRMATIONS ====================
    areYouSure: "Êtes-vous sûr ?",
    confirmDelete: "Êtes-vous sûr de vouloir supprimer ceci ?", 
    confirmAction: "Êtes-vous sûr de vouloir continuer ?",
    cannotBeUndone: "Cette action ne peut pas être annulée",
    yes: "Oui",
    no: "Non",
    // ==================== SUCCESS MESSAGES ====================
    success: "Succès",
    operationSuccessful: "Opération réussie",
    savedSuccessfully: "Enregistré avec succès",
    deletedSuccessfully: "Supprimé avec succès",
    updatedSuccessfully: "Mis à jour avec succès",
    createdSuccessfully: "Créé avec succès",
    // ==================== ERROR MESSAGES ====================
    error: "Erreur",
    somethingWentWrong: "Quelque chose a mal tourné",
    errorOccurred: "Une erreur s'est produite",
    tryAgain: "Veuillez réessayer",
    contactSupport: "Contactez le support si le problème persiste",
    networkError: "Erreur réseau. Veuillez vérifier votre connexion",
    unauthorized: "Accès non autorisé",
    accessDenied: "Accès refusé",
    notFound: "Non trouvé",
    // ==================== NOTIFICATIONS ====================
    notifications: "Notifications",
    noNotifications: "Aucune notification",
    markAsRead: "Marquer comme lu",
    markAllAsRead: "Marquer tout comme lu",
    clearAll: "Tout effacer", 
    // ==================== HELP & INFO ====================
    help: "Aide",
    documentation: "Documentation",
    support: "Support",
    contactUs: "Contactez-nous",
    faq: "FAQ",
    // ==================== FOOTER ====================
    allRightsReserved: "Tous droits réservés",
    privacyPolicy: "Politique de confidentialité",
    termsOfService: "Conditions d'utilisation",
    version: "Version",
  },
  ar: {
    // ==================== NAVIGATION ====================
    dashboard: "لوحة التحكم",
    myTickets: "تذاكري",
    allTickets: "جميع التذاكر",
    services: "الخدمات",
    users: "المستخدمون",
    departments: "الأقسام",
    roles: "الأدوار",
    logout: "تسجيل الخروج",
    profile: "الملف الشخصي",
    settings: "الإعدادات",
    // ==================== COMMON ACTIONS ====================
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    activate: "تفعيل",
    deactivate: "تعطيل",
    add: "إضافة",
    create: "إنشاء",
    update: "تحديث",
    submit: "إرسال",
    close: "إغلاق",
    back: "رجوع",
    next: "التالي",
    previous: "السابق",
    confirm: "تأكيد",
    search: "بحث",
    filter: "تصفية",
    reset: "إعادة تعيين",
    clear: "مسح",
    apply: "تطبيق",
    download: "تحميل",
    upload: "رفع",
    export: "تصدير",
    import: "استيراد",
    print: "طباعة",
    refresh: "تحديث",
    // ==================== COMMON PHRASES ====================
    welcome: "مرحبًا", 
    welcomeBack: "مرحبًا بعودتك",
    loading: "جار التحميل...",
    noData: "لا توجد بيانات متاحة",
    noResults: "لم يتم العثور على نتائج",
    searchResults: "نتائج البحث",
    showing: "عرض", 
    of: "من",
    results: "نتائج",
    page: "صفحة",
    rowsPerPage: "الصفوف في الصفحة",
    selectAll: "تحديد الجميع",
    selected: "محدد",
    submittedBy: "مقدم الطلب",
    title: "العنوان",
    // ==================== FORM FIELDS ====================
    yourName: "اسمك",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    phone: "الهاتف",
    address: "العنوان",
    city: "المدينة",
    country: "البلد",
    postalCode: "الرمز البريدي",
    dateOfBirth: "تاريخ الميلاد",
    gender: "الجنس",  
    male: "ذكر",
    female: "أنثى",
    describeInDetail: "وصف طلبك بالتفصيل...",
    // ==================== VALIDATION MESSAGES ====================
    required: "هذا الحقل مطلوب",
    invalidEmail: "تنسيق البريد الإلكتروني غير صالح",
    invalidPhone: "رقم الهاتف غير صالح",
    passwordMismatch: "كلمات المرور غير متطابقة",
    passwordTooShort: "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
    fieldRequired: "جميع الحقول مطلوبة",
    pleaseSelect: "يرجى الاختيار",
    selectOption: "اختر خيارًا",
    // ==================== AUTH & LOGIN ====================
    login: "تسجيل الدخول",
    loginTitle: "تسجيل الدخول إلى حسابك",
    register: "التسجيل",
    registerTitle: "إنشاء حساب جديد",
    forgotPassword: "هل نسيت كلمة المرور؟",
    rememberMe: "تذكرني",
    dontHaveAccount: "ليس لديك حساب؟",
    alreadyHaveAccount: "هل لديك حساب بالفعل؟",
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    signOut: "تسجيل الخروج",
    // ==================== TICKETS ====================  
    ticket: "تذكرة",
    tickets: "تذاكر",
    newTicket: "طلب جديد",
    createTicket: "إنشاء تذكرة",
    submitRequest: "إرسال الطلب",
    ticketDetails: "تفاصيل التذكرة",
    ticketNumber: "رقم التذكرة",
    ticketTitle: "عنوان الطلب",
    ticketDescription: "الوصف",
    ticketCreated: "تم إنشاء التذكرة",  
    ticketUpdated: "تم تحديث التذكرة",
    ticketClosed: "تم إغلاق التذكرة",
    noTickets: "لا توجد تذاكر حتى الآن. قدم طلبك الأول!",
    noTicketsFound: "لم يتم العثور على تذاكر",
    trackYourRequests: "تتبع جميع طلباتك المقدمة",
    fillDetailsBelow: "املأ التفاصيل أدناه لتقديم طلبك",
    describeInDetail: "وصف طلبك بالتفصيل...",
    ticketSubmittedSuccess: "تم تقديم التذكرة بنجاح! جاري إعادة التوجيه...",
    assignToMe: "تعيين لي",
    assignedToYou: "تم تعيينه لك",
    unassigned: "غير معين",
    manageResolveTickets: "إدارة وحل التذاكر المخصصة لك",
      // ==================== PRIORITY ==================== 
    priority: "الأولوية",
    low: "منخفضة",
    medium: "متوسطة",
    high: "عالية",
    critical: "حرجة",
    urgent: "عاجلة",
    // ==================== STATUS ====================
    status: "الحالة",
    active: "نشط",
    inactive: "غير نشط",
    pending: "قيد الانتظار",
    approved: "موافق عليه",
    rejected: "مرفوض",
    all: "الكل",
    new: "جديد",
    assigned: "معين",
    in_progress: "قيد التنفيذ",
    resolved: "تم الحل",
    closed: "مغلق",
    open: "مفتوح",
    completed: "مكتمل",
    // ==================== USERS ====================
    user: "المستخدم",
    userName: "اسم المستخدم",
    fullName: "الاسم الكامل",
    role: "الدور",
    department: "القسم",
    agentDashboard: "لوحة تحكم الوكيل",
    totalUsers: "إجمالي المستخدمين",
    activeUsers: "المستخدمون النشطون",
    pendingUsers: "في انتظار التفعيل",
    userManagement: "إدارة المستخدمين",
    addUser: "إضافة مستخدم",
    addNewUser: "إضافة مستخدم جديد",
    editUser: "تعديل المستخدم",
    deleteUser: "حذف المستخدم",
    activateUser: "تفعيل المستخدم",
    deactivateUser: "تعطيل المستخدم",
    userCreated: "تم إنشاء المستخدم بنجاح",
    userUpdated: "تم تحديث المستخدم بنجاح",
    userDeleted: "تم حذف المستخدم بنجاح",
    searchUsers: "البحث عن المستخدمين...",
    noUsersFound: "لم يتم العثور على مستخدمين",
    allUsers: "جميع المستخدمين",
    pendingActivation: "في انتظار التفعيل",
    // ==================== DEPARTMENTS ====================
    departmentManagement: "إدارة الأقسام",
    departmentName: "اسم القسم",
    departmentHead: "رئيس القسم",
    addDepartment: "إضافة قسم",
    editDepartment: "تعديل القسم",
    deleteDepartment: "حذف القسم",
    noDepartments: "لم يتم العثور على أقسام",
    saveChanges: "حفظ التغييرات",
    selectDepartment: "اختر قسمًا",
    // ==================== ROLES ====================
    roleName: "اسم الدور",
    roleDescription: "وصف الدور",
    permissions: "الأذونات",
    addRole: "إضافة دور",
    editRole: "تعديل الدور",
    deleteRole: "حذف الدور",
    noRoles: "لم يتم العثور على أدوار",
    roleManagement: "إدارة الأدوار",
    selectRole: "اختر دورًا",
    // ==================== SERVICES ====================
    service: "الخدمة",
    serviceName: "اسم الخدمة",
    serviceDescription: "وصف الخدمة",
    serviceCategory: "فئة الخدمة",
    serviceCatalog: "كتالوج الخدمات",
    browseServices: "تصفح الخدمات",
    requestService: "طلب خدمة",
    addService: "إضافة خدمة",
    editService: "تعديل الخدمة",
    deleteService: "حذف الخدمة",
    noServices: "لا توجد خدمات متاحة",
    selectService: "اختر خدمة",
    slaHours: "س SLA",
    expectedResolution: "الحل المتوقع",
    hours: "ساعات",
      // ==================== CATEGORIES ==================== 
    category: "الفئة",
    hardware: "الأجهزة",
    software: "البرمجيات",
    network: "الشبكة",
    account: "الحساب",
    access: "الوصول",
    security: "الأمان",
    support: "الدعم",
    maintenance: "الصيانة",
    other: "أخرى",
    // ==================== DASHBOARD ====================
    manageOrganization: "إدارة منظمتك من خلال هذه اللوحة",
    quickOverview: "نظرة سريعة",
    recentActivity: "النشاط الأخير",
    statistics: "الإحصائيات",
    analytics: "التحليلات",
    reports: "التقارير",
    // ==================== STATS CARDS ====================
    total: "المجموع",
    today: "اليوم",
    thisWeek: "هذا الأسبوع",
    thisMonth: "هذا الشهر",
    newRequests: " الطلبات الجديدة",
    pendingApproval: "قيد الانتظار للموافقة",
    resolvedToday: "تم حلها اليوم",
    averageResponseTime: "متوسط وقت الاستجابة",
    // ==================== ACTIONS ====================
    viewDetails: "عرض التفاصيل",
    moreInfo: "مزيد من المعلومات",
    actions: "الإجراءات",
    options: "الخيارات",
    manage: "إدارة",
    configure: "تكوين",
    // ==================== TIME & DATE ====================
    createdAt: "تم الإنشاء في",
    updatedAt: "تم التحديث في",
    createdBy: "تم الإنشاء بواسطة",
    assignedTo: "تم تعيينه إلى",
    resolvedAt: "تم الحل في",
    closedAt: "تم الإغلاق في",
    date: "التاريخ",
    time: "الوقت",
    dateTime: "التاريخ والوقت",
    // ==================== CONFIRMATIONS ====================
    areYouSure: "هل أنت متأكد؟",
    confirmDelete: "هل أنت متأكد من رغبتك في حذف هذا العنصر؟", 
    confirmAction: "هل أنت متأكد من رغبتك في الاستمرار؟",
    cannotBeUndone: "لا يمكن التراجع عن هذه العملية.",
    yes: "نعم",
    no: "لا",
    // ==================== SUCCESS MESSAGES ====================
    success: "نجاح",
    operationSuccessful: "تمت العملية بنجاح",
    savedSuccessfully: "تم الحفظ بنجاح",
    deletedSuccessfully: "تم الحذف بنجاح",
    updatedSuccessfully: "تم التحديث بنجاح",
    createdSuccessfully: "تم الإنشاء بنجاح",
    // ==================== ERROR MESSAGES ====================   
    error: "خطأ",
    somethingWentWrong: "حدث خطأ ما",
    errorOccurred: "حدث خطأ",
    tryAgain: "يرجى المحاولة مرة أخرى",
    contactSupport: "اتصل بالدعم إذا استمرت المشكلة",
    networkError: "خطأ في الشبكة. يرجى التحقق من اتصالك",
    unauthorized: "وصول غير مصرح به",
    accessDenied: "تم رفض الوصول",
    notFound: "غير موجود",
    // ==================== NOTIFICATIONS ====================  
    notifications: "الإشعارات",
    noNotifications: "لا توجد إشعارات",
    markAsRead: "وضع علامة كمقروء",
    markAllAsRead: "وضع علامة للجميع كمقروء",
    clearAll: "مسح الجميع",
    // ==================== HELP & INFO ====================    
    help: "مساعدة",
    documentation: "التوثيق",
    support: "الدعم",
    contactUs: "اتصل بنا",
    faq: "الأسئلة الشائعة",
    // ==================== FOOTER ====================
    allRightsReserved: "جميع الحقوق محفوظة",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الخدمة",
    version: "الإصدار",
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("language") || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    // Set direction for Arabic
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);